name: bookly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  font_awesome_flutter: ^10.10.0
  go_router: ^16.2.5
  google_fonts: ^6.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  analyzer: ^6.4.1
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logos/
    - assets/images/

  fonts:
    - family: Sectra
      fonts:
        - asset: assets/fonts/GT-Sectra-Fine-Regular-Trial.otf
